### ISSUE TITLE
Promise api?

### ISSUE THREAD

**Issue by apechimp** [yammer/circuit-breaker-js#2]
The api for `run` as it stands is equivalent to accepting a [constructor of a promise](https://github.com/petkaantonov/bluebird/blob/master/API.md#new-promisefunctionfunction-resolve-function-reject-resolver---promise). Would you be open to a PR which allows for accepting a promise as well?

**Comment by codan84** [comment]
+1 this, API with Promises would be a step forward

**Comment by dsummersl** [comment]
+1

**Comment by apechimp** [comment]
I didn't get any response from the maintainers and it seems a little unreasonable to add a promise library as a dependency since the current consumers don't use promises, so I made a [module](https://www.npmjs.com/package/circuit-breaker-as-promised) which wraps this one, providing a promise api.
