### ISSUE TITLE
Catch errors in run()?

### ISSUE THREAD

**Issue by dsummersl** [yammer/circuit-breaker-js#4]
I recently discovered my implementation was throwing an exception before calling the `success` or `failure` methods. Personally I'd expect that circuit-breaker would take that to mean failure. How to reproduce:

```js
var breaker = new CircuitBreaker();
breaker.run(function(success, failed) {
  throw new Error("uncaught error");
});
```

How I'm fixing this now:

```js
var breaker = new CircuitBreaker();
breaker.run(function(success, failed) {
  try {
    throw new Error("example");
  } catch (e) {
    failed();
  }
});
```

Would it make sense to add this behavior to the circuit-breaker library?

**Comment by sublimino** [comment]
IMO this functionality should be handled by the application, not the circuit breaker.

An application might want to force the circuit open for a period of time for certain exception types, or ignore others that represent a transient error. If exceptions are caught by the breaker the application has no chance to handle them.
